# Generated by Django 5.2.7 on 2025-10-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trinamento',
            new_name='Treinamento',
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('VÍDEO', 'Video'), ('ZIP', 'ZIP')], max_length=10),
        ),
    ]
