# Generated by Django 5.2.7 on 2025-10-28 12:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_rename_trinamento_treinamento_alter_recurso_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome'], 'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['-data_matricula'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterModelOptions(
            name='recurso',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterModelOptions(
            name='treinamento',
            options={'ordering': ['nome'], 'verbose_name': 'Treinamento', 'verbose_name_plural': 'Treinamentos'},
        ),
        migrations.AlterModelOptions(
            name='turma',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Turma', 'verbose_name_plural': 'Turmas'},
        ),
        migrations.AddField(
            model_name='matricula',
            name='data_matricula',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Matrícula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recurso',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='classroom.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='classroom.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='acesso_previo',
            field=models.BooleanField(default=False, help_text='Permite acesso antes da data de início da turma', verbose_name='Acesso Prévio'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='draft',
            field=models.BooleanField(default=False, help_text='Recurso em modo rascunho (não visível para alunos)', verbose_name='Rascunho'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('PDF', 'PDF'), ('VIDEO', 'Vídeo'), ('ZIP', 'Arquivo ZIP')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='classroom.turma', verbose_name='Turma'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='link_acesso',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Acesso'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='treinamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='classroom.treinamento', verbose_name='Treinamento'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
    ]
