# Generated by Django 5.2.7 on 2025-10-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_aluno_options_alter_matricula_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_conclusao',
            field=models.DateField(null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='link_acesso',
            field=models.URLField(null=True, verbose_name='Link de Acesso'),
        ),
    ]
