# Generated by Django 5.2.7 on 2025-10-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_alter_turma_data_conclusao_alter_turma_link_acesso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
    ]
